### ISSUE TITLE
[BUG] Killaura CPS

### ISSUE THREAD

**Issue by sunforst** [ManInMyVan/SkidBounce#30]
Max cps 20
Min cps 20
**Screenshots**
![image](https://github.com/ManInMyVan/SkidBounce/assets/174558960/bb7539b9-cf17-4d96-b4b9-438cd5245eb5)

**Comment by sunforst** [comment]
i think the problem is the switch, cause works good on single and multi.

**Comment by ManInMyVan** [comment]
it doesn't want to miss while switching targets, nothing is wrong here
